name: 'Git Tag Generator'
description: 'Bump and push git tag on push/merge with specified commit message'
author: 'Chloe Zhang'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  last_tag:
    description: 'The latest tag before running this action'
  new_tag:
    description: 'Newly generated tag'
branding:
  icon: 'tag'  
  color: 'yellow'
